source 'https://github.com/CocoaPods/Specs.git'


target 'HealthKitIO', :exclusive => true do
  pod "HealthKitIO", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'NSObject-Tap'
  pod 'VVJSONSchemaValidation'
end
